# Layouts to use.
layouts:
  - tall
  - fullscreen
  - wide
  - column

# First modifer key for commands.
mod1:
  - option

# Second modifer key for commands.
mod2:
  - option
  - shift

# Move to the next layout in the list.
cycle-layout:
  mod: mod1
  key: space

# Move to the previous layout in the list.
cycle-layout-backward:
  mod: mod2
  key: space

# Shrink the main pane.
shrink-main:
  mod: mod1
  key: h

# Expand the main pane.
expand-main:
  mod: mod1
  key: l

# Increase the number of windows in the main pane. 
increase-main:
  mod: mod1
  key: ','

# Decrease the number of windows in the main pane. 
decrease-main:
  mod: mod1
  key: '.'

# Focus window counter-clockwise.
focus-ccw:
  mod: mod1
  key: up

# Focus window clockwise.
focus-cw:
  mod: mod1
  key: down

# Focus main window.
focus-main:
  mod: mod1
  key: left

# Focus screen counter-clockwise.
focus-screen-ccw:
  mod: mod1
  key: p

# Focus screen clockwise. 
focus-screen-cw:
  mod: mod1
  key: n

# Move focussed window to screen counter-clockwise. 
swap-screen-ccw:
  mod: mod2
  key: h

# Move focussed window to screen clockwise.
swap-screen-cw:
  mod: mod2
  key: l

# Swap window counter-clockwise.
swap-ccw:
  mod: mod2
  key: up

# Swap window clockwise.
swap-cw:
  mod: mod2
  key: down

# Swap window with main.
swap-main:
  mod: mod2
  key: left


# Move focus to the n-th screen in the list; e.g., focus-screen-3 will move mouse focus to the 3rd screen. Note that the main window in the given screen will be focused.
#focus-screen-n:
# focus-screen-<screen-number>:
#   mod: mod1
#   key: y
# Move the currently focused window to the n-th screen; e.g., throw-screen-3 will move the window to the 3rd screen.
# throw-screen-n:
# throw-screen-<screen-number>:
#   mod: mod1
#   key: u
# Move the currently focused window to the n-th space; e.g., throw-space-3 will move the window to the 3rd space.

# Throw window to 1st space.
throw-space-1:
  mod: mod2
  key: 1

# Throw window to 2nd space.
throw-space-2:
  mod: mod2
  key: 2

# Throw window to 3rd space.
throw-space-3:
  mod: mod2
  key: 3

# Throw window to 4th space.
throw-space-4:
  mod: mod2
  key: 4

# Throw window to 5th space.
throw-space-5:
  mod: mod2
  key: 5

# Throw window to 6th space.
throw-space-6:
  mod: mod2
  key: 6

# Throw window to 7th space.
throw-space-7:
  mod: mod2
  key: 7

# Throw window to 8th space.
throw-space-8:
  mod: mod2
  key: 8

# Throw window to 9th space.
throw-space-9:
  mod: mod2
  key: 9

# Throw window to 10th space.
throw-space-0:
  mod: mod2
  key: 0

# Select tall layout
select-tall-layout:
  mod: mod1
  key: a

# Select wide layout
select-wide-layout:
  mod: mod1
  key: s

# Select fullscreen layout
select-fullscreen-layout:
  mod: mod1
  key: d

# Select column layout
select-column-layout:
  mod: mod1
  key: f

# Move window to space on left.
throw-space-left:
  mod: mod2
  key: j

# Move window to space on right. 
throw-space-right:
  mod: mod2
  key: k

# Toggle window floating. 
toggle-float:
  mod: mod1
  key: t

# Display current layout.
display-current-layout:
  mod: mod1
  key: i

# Turn on or off tiling entirely.
toggle-tiling:
  mod: mod2
  key: '`'

# Rerun the current layout's algorithm.
reevaluate-windows:
  mod: mod1
  key: z

# Turn on or off focus-follows-mouse.
toggle-focus-follows-mouse:
  mod: mod2
  key: '`'

# Automatically quit and reopen Amethyst.
relaunch-amethyst:
  mod: mod2
  key: z

# disable screen padding on builtin display
disable-padding-on-builtin-display: false

# Boolean flag for whether or not to add margins between windows (default false).
window-margins: false

# Boolean flag for whether or not to set window margins if there is only one window on the screen, assuming window margins are enabled (default false).
smart-window-margins: false

# # Add 10px margin between windows
# window-margins: true
# window-margin-size: 5
# The size of the margins between windows (in px, default 0).
window-margin-size: 0

# The max number of windows that may be visible on a screen at one time before
# additional windows are minimized. A value of 0 disables the feature.
window-max-count: 0

# The smallest height that a window can be sized to regardless of its layout frame (in px, default 0).
window-minimum-height: 0

# The smallest width that a window can be sized to regardless of its layout frame (in px, default 0)
window-minimum-width: 0

# List of bundle identifiers for applications to either be automatically floating or automatically tiled based on floating-is-blacklist (default []).
floating: []

# Boolean flag determining behavior of the floating list. true if the applications should be floating and all others tiled. false if the applications should be tiled and all others floating (default true).
floating-is-blacklist: true

# true if screen frames should exclude the status bar. false if the screen frames should include the status bar (default false).
ignore-menu-bar: false

# true if menu bar icon should be hidden (default false).
hide-menu-bar-icon: false

# true if windows smaller than a 500px square should be floating by default (default true)
float-small-windows: false

# true if the mouse should move position to the center of a window when it becomes focused (default false). Note that this is largely incompatible with focus-follows-mouse.
mouse-follows-focus: false

# true if the windows underneath the mouse should become focused as the mouse moves (default false). Note that this is largely incompatible with mouse-follows-focus
focus-follows-mouse: true

# true if dragging and dropping windows on to each other should swap their positions (default false).
mouse-swaps-windows: true

# true if changing the frame of a window with the mouse should update the layout to accommodate the change (default false). Note that not all layouts will be able to respond to the change.
mouse-resizes-windows: true

# true to display the name of the layout when a new layout is selected (default true).
enables-layout-hud: true

# true to display the name of the layout when moving to a new space (default true).
enables-layout-hud-on-space-change: true

# true to get updates to beta versions of the software (default false).
use-canary-build: false

# true to insert new windows into the first position and false to insert new windows into the last position (default false).
new-windows-to-main: false

# true to automatically move to a space when throwing a window to it (default true).
follow-space-thrown-windows: false

# The integer percentage of the screen dimension to increment and decrement main pane ratios by (default 5).
window-resize-step: 5

# Padding to apply between windows and the left edge of the screen (in px, default 0).
screen-padding-left: 0

# Padding to apply between windows and the right edge of the screen (in px, default 0).
screen-padding-right: 0

# Padding to apply between windows and the top edge of the screen (in px, default 0).
screen-padding-top: 0

# Padding to apply between windows and the bottom edge of the screen (in px, default 0).
screen-padding-bottom: 0

# true to maintain layout state across application executions (default true).
restore-layouts-on-launch: false

# true to display some optional debug information in the layout HUD (default false).
debug-layout-info: true
